name: Update CEBL Data

on:
  #schedule:
   # - cron: '5 4 * * *' # This runs the workflow daily at midnight UTC
  workflow_dispatch:
  #push:
   # branches:
    #  - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install Packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::pacman
            any::devtools
            
      - name: ceblscrapeR Installation
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        run: Rscript -e 'devtools::install_github("awosoga/ceblscrapeR")'
      - name: Update Boxscores # refresh_data
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        run: Rscript -e 'source("R/update_boxscores.R")'
      - name: Update League Factors # refresh_data
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        run: Rscript -e 'source("R/update_league_factors.R")'
      - name: Update Advanced Data # refresh_data
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        run: Rscript -e 'source("R/update_advanced_data.R")'

